# Generated by Django 4.2.7 on 2023-11-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketmaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('passWord', models.CharField(max_length=50)),
                ('eventCart', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
