# Generated by Django 4.2.7 on 2023-12-01 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketmaster', '0002_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='description',
            new_name='Name',
        ),
    ]
